### ISSUE TITLE
TAAK: Op de overzichtspagina wil ik de gegevens van members van een bepaalde squad ingeladen hebben

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#16]

**Comment by Naddybs** [comment]
[Commit voorbeeld](https://github.com/Khdulkadir/your-tribe-for-life-squad-page/commit/a076eaa23db698fb37b197ac6efa8003ada448b7)

_In de bovenstaande  commit kan je een voorbeeld zien van hoe ik de gegevens van squadmembers heb opgehaald en weergegeven._

### Hoe heb ik dit bereikt?

**`Data ophalen`**

- Allereerst heb ik een helperfunctie, fetchJson opgesteld om data van een API op te halen en in JSON formaat terug te geven.
- Vervolgens heb ik deze functie geimplementeerd in de page.server.js, waar ik de API link heb gedefinieerd om squadmembers op basis van hun squad id op te halen. 
- Met de fetchjson functie haalde ik de data op en retourneerde deze als persons. Als er geen data beschikbaar is wordt er een foutmelding teruggegeven.

**`Data weergeven`**

- In de +page.svelte heb ik deze data via export let data geimporteerd.
- Vervolgens heb ik met Sveltes each loop de  persons data op de pagina weergegeven.
- Elke member van de squad wordt weergegeven door een card component aan te roepen en de relevante info zoals bvb de naam etc door te geven als props aan de card.

![Image](https://github.com/user-attachments/assets/84dd9ba2-5ac2-4630-8ec9-45ce523d3d85)
