### ISSUE TITLE
TAAK: Op de detailpagina wil ik de gegevens van een specifieke member ingeladen hebben

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#22]

**Comment by Khdulkadir** [comment]
Gegevens worden ingeladen van de database van directus met de volgende code:

`
import fetchJson from "$lib/fetch-json";
import { error } from '@sveltejs/kit';

export async function load({ params }) {
  const url =`https://fdnd.directus.app/items/person/?filter={"id":${params.id}}`;

  const response = await fetchJson(url);

  // If the persons array is empty, throw a 404 error
  if (!response.data || response.data.length === 0) {
    throw error(404, `Person with ID ${params.id} not found`);
  }

  return {
    persons: response.data,
  };
}
`


En het wordt getoond op de frontend met de volgende code:

`
      <h1>{data.persons[0].name} {data.persons[0].prefix} {data.persons[0].surname}</h1>

`
