### ISSUE TITLE
Toegankelijkheid en browser test en verbeteren detailpagina

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#27]

**Comment by Khdulkadir** [comment]
Toegankelijkheidstest:
Alle teksten op de detailpagina hebben de kleurcontrasttest voltooid.
Ook heeft de detailpagina de tabtest succesvol voltooid.

Browsertest:
Op chromium browsers werkt de detailpagina goed, zelfs op oudere versies.

Op ios verdwijnt de pokeball niet en is de pokeball niet gecentreerd:

![Image](https://github.com/user-attachments/assets/2e176c1f-1450-41d7-8536-1745d8425ecc)

Pokeball is weer gecentreerd door ipv:
```
  main {
    display: grid;
    place-items: center;
    height: 100vh;
  }
```

dit te doen:
```
  main {
    display: flex;
    justify-content: center;
    height: 100vh;
    align-items: center;
  }
```
