### ISSUE TITLE
Lighthouse test detailpagina en verbeteren

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#28]

**Comment by Khdulkadir** [comment]
Testresultaten:
![Image](https://github.com/user-attachments/assets/bb91de85-d53a-48a8-bc5d-431d914ffadc)

Aanpassingen toegepast:
`      <img class="card-type" src="/assets/card-type.png" alt="card type" height="20">
`
width attribute gegeven.

--------------------------

pikachu.png formaat verkleind van 512x512 naar 200x200.

--------------------------
