### ISSUE TITLE
Als gebruiker wil ik een hover animation voor de pokemon cards zodat ik weet dat het kaartje kan omdraaien

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#3]
Maak een hover effect als de gebruiker over een kaartje hovered, zorg dat het kaartje omdraaid en dat de naam + unlock button komt te staan

**Comment by RubenErhardt** [comment]
https://github.com/latoyaln/squad-page-zes/issues/15

**Comment by Naddybs** [comment]
[Commit voorbeeld](https://github.com/Khdulkadir/your-tribe-for-life-squad-page/commit/2eda975b7b66472e553e5685698d907f9d3daf26)

In de bovenstaande commit laat ik zien hoe ik ervoor heb gezorgd dat de pokemon kaarten een hover animatie krijgen, zodat de gebruiker kan zien dat de kaart omgedraaid kan worden.

### Hoe heb ik dit bereikt?

- Ik heb eerst een component opgesteld in de Card.svelte file. Hier heb ik de stijlen van de kaarten gedefinieerd die ik later hergebruik in de page.svelte. Ik heb hier de voor- en achterkant van de kaarten apart gestyled.
- Vervolgens heb ik css transformations toegevoegd om de kaart te laten draaien bij een hover. Door de voor- en  achterkant van de kaart te positioneren met backface visibility: hidden en rotate(180deg), heb ik ervoor gezorgd dat de kaart omdraait wanneer de gebruiker er met de muis overheen gaat. Dit gebeurt met een overgangseffect dankzij transition transform.
- Tot slot heb ik met de :hover selector ervoor gezorgd dat de kaart bij hover omdraait. De voorkant van de kaart wordt verborgen en de achterkant wordt zichtbaar zodra de muis eroverheen gaat, waardoor het lijkt alsof de kaart daadwerkelijk omdraait.

<img width="900" alt="Scherm­afbeelding 2024-09-17 om 20 35 31" src="https://github.com/user-attachments/assets/0a4f7b07-965e-46ce-86ec-e5950640f361">

<img width="900" alt="Scherm­afbeelding 2024-09-17 om 20 35 48" src="https://github.com/user-attachments/assets/46df765d-2fef-491f-9220-844481917750">
