### ISSUE TITLE
verschillende designs homepagina

### ISSUE THREAD

**Issue by RubenErhardt** [Khdulkadir/your-tribe-for-life-squad-page#32]

**Comment by latoyaln** [comment]
Ik heb een schets gemaakt van hoe de homepage eruit moet zien. Hier heb ik vervolgens een mobiele versie van gemaakt
![Mobile Version Schets](https://github.com/user-attachments/assets/4a2e8ce7-3f0d-44c5-8aae-f677d54ed19c)
![FDND Squadpage](https://github.com/user-attachments/assets/772fbf11-199c-4e97-9e06-fd88201446e7)
